"""renamed year to publication_year

Revision ID: 909ee626fc07
Revises: 80aefb0df928
Create Date: 2025-06-13 11:46:54.611012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909ee626fc07'
down_revision = '80aefb0df928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('publication_year')

    # ### end Alembic commands ###
